export const AUTH_USERS = [
  {
    email: "admin@flybiz.io",
    password: "admin123",
    role: "admin",
    name: "Alex Admin",
  },
  {
    email: "manager@flybiz.io",
    password: "manager123",
    role: "manager",
    name: "Maria Manager",
  },
  {
    email: "mod@flybiz.io",
    password: "mod123",
    role: "moderator",
    name: "Mike Mod",
  },
];

export interface MockUser {
  id: number;
  name: string;
  email: string;
  role: "admin" | "manager" | "moderator";
  plan: "free" | "pro" | "enterprise";
  aiGenerations: number;
  status: "active" | "inactive" | "suspended";
  initials: string;
  avatarColor: string;
  joinDate: string;
}

export const MOCK_USERS: MockUser[] = [
  {
    id: 1,
    name: "Sophia Bennett",
    email: "sophia@acme.com",
    role: "admin",
    plan: "enterprise",
    aiGenerations: 1240,
    status: "active",
    initials: "SB",
    avatarColor: "bg-blue-500",
    joinDate: "Jan 12, 2024",
  },
  {
    id: 2,
    name: "James Rivera",
    email: "james@techco.io",
    role: "manager",
    plan: "pro",
    aiGenerations: 893,
    status: "active",
    initials: "JR",
    avatarColor: "bg-purple-500",
    joinDate: "Feb 3, 2024",
  },
  {
    id: 3,
    name: "Elena Vasquez",
    email: "elena@brandlab.co",
    role: "moderator",
    plan: "pro",
    aiGenerations: 421,
    status: "active",
    initials: "EV",
    avatarColor: "bg-pink-500",
    joinDate: "Mar 7, 2024",
  },
  {
    id: 4,
    name: "Marcus Chen",
    email: "marcus@startupx.ai",
    role: "manager",
    plan: "enterprise",
    aiGenerations: 2105,
    status: "active",
    initials: "MC",
    avatarColor: "bg-green-500",
    joinDate: "Jan 28, 2024",
  },
  {
    id: 5,
    name: "Ava Thompson",
    email: "ava@growthco.io",
    role: "moderator",
    plan: "free",
    aiGenerations: 47,
    status: "inactive",
    initials: "AT",
    avatarColor: "bg-yellow-500",
    joinDate: "Apr 15, 2024",
  },
  {
    id: 6,
    name: "Noah Williams",
    email: "noah@webcraft.co",
    role: "admin",
    plan: "enterprise",
    aiGenerations: 3892,
    status: "active",
    initials: "NW",
    avatarColor: "bg-blue-600",
    joinDate: "Dec 10, 2023",
  },
  {
    id: 7,
    name: "Isabella Moore",
    email: "isabella@designpro.io",
    role: "moderator",
    plan: "pro",
    aiGenerations: 634,
    status: "active",
    initials: "IM",
    avatarColor: "bg-rose-500",
    joinDate: "May 2, 2024",
  },
  {
    id: 8,
    name: "Liam Jackson",
    email: "liam@contentfactory.co",
    role: "manager",
    plan: "pro",
    aiGenerations: 1124,
    status: "suspended",
    initials: "LJ",
    avatarColor: "bg-indigo-500",
    joinDate: "Feb 20, 2024",
  },
  {
    id: 9,
    name: "Mia Davis",
    email: "mia@pixelstudio.io",
    role: "moderator",
    plan: "free",
    aiGenerations: 89,
    status: "active",
    initials: "MD",
    avatarColor: "bg-teal-500",
    joinDate: "Jun 1, 2024",
  },
  {
    id: 10,
    name: "Ethan Wilson",
    email: "ethan@adagency.com",
    role: "manager",
    plan: "enterprise",
    aiGenerations: 1876,
    status: "active",
    initials: "EW",
    avatarColor: "bg-orange-500",
    joinDate: "Mar 15, 2024",
  },
  {
    id: 11,
    name: "Charlotte Brown",
    email: "charlotte@marketingpro.io",
    role: "moderator",
    plan: "pro",
    aiGenerations: 312,
    status: "inactive",
    initials: "CB",
    avatarColor: "bg-violet-500",
    joinDate: "Apr 28, 2024",
  },
  {
    id: 12,
    name: "Oliver Martinez",
    email: "oliver@socialboost.co",
    role: "manager",
    plan: "pro",
    aiGenerations: 756,
    status: "active",
    initials: "OM",
    avatarColor: "bg-cyan-500",
    joinDate: "Jan 5, 2024",
  },
  {
    id: 13,
    name: "Amelia Anderson",
    email: "amelia@brandstudio.ai",
    role: "moderator",
    plan: "free",
    aiGenerations: 23,
    status: "suspended",
    initials: "AA",
    avatarColor: "bg-fuchsia-500",
    joinDate: "Jul 10, 2024",
  },
  {
    id: 14,
    name: "William Taylor",
    email: "william@creativehub.io",
    role: "admin",
    plan: "enterprise",
    aiGenerations: 2340,
    status: "active",
    initials: "WT",
    avatarColor: "bg-sky-500",
    joinDate: "Nov 22, 2023",
  },
  {
    id: 15,
    name: "Harper Garcia",
    email: "harper@futureads.co",
    role: "moderator",
    plan: "pro",
    aiGenerations: 445,
    status: "active",
    initials: "HG",
    avatarColor: "bg-lime-500",
    joinDate: "May 18, 2024",
  },
  {
    id: 16,
    name: "Benjamin Lee",
    email: "ben@scalestudio.io",
    role: "manager",
    plan: "enterprise",
    aiGenerations: 1598,
    status: "active",
    initials: "BL",
    avatarColor: "bg-emerald-500",
    joinDate: "Feb 14, 2024",
  },
];
